name : Pipeline

on:
  push : 
    branches : 
      - main
    paths : 
      - 'docker-compose-server.yml' 
      - 'backend/**'
      - 'frontend/**'
      - 'nginx.conf'
      - '.github/workflows/ci.yml'
  
  pull_request : 
    branches : 
      - main
      - dev
      - 'release/*'
    paths : 
      - 'docker-compose.yml' 
      - 'backend/**'
      - 'frontend/**'
      - 'nginx.conf'
      - '.github/workflows/ci.yml'



env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  REPOSITORY: maeldem/projet_devops

jobs : 

  linting : 
    if: github.event_name == 'pull_request'
    runs-on : ubuntu-latest
    timeout-minutes: 15
  
    steps : 
      - name : Checkout branch
        uses : actions/checkout@v4
        with: 
          fetch-depth: 0

      - name : Setup Bun
        uses : oven-sh/setup-bun@v2

      - name : Install dependencies
        run : bun install
      
      - name : Run Linters
        run : | 
          bun run check 
          bun run ci

      - name: Commit changes if any
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git diff --exit-code || {
            echo "Changes detected. Committing changes..."

              git config --global user.name "github-actions"
              git config --global user.email "actions@github.com"

              git add .
              git commit -m "Apply code formatting and linting fixes"
              git push origin HEAD
            }
  
  test-frontend :

    needs : linting
    if: github.event_name == 'pull_request'
    runs-on : ubuntu-latest
    timeout-minutes: 15

    steps : 
      - name : Checkout branch
        uses : actions/checkout@v4
        with: 
          fetch-depth: 0

      - name : Setup Bun
        uses : oven-sh/setup-bun@v2

      - name : Install dependencies
        run : bun install
        working-directory: ./frontend


      - name : Run tests  
        run : bun test
        working-directory: ./frontend


  test-backend : 

    needs : linting
    if: github.event_name == 'pull_request'
    runs-on : ubuntu-latest
    timeout-minutes: 15

    steps : 
      - name : Checkout branch
        uses : actions/checkout@v4
        with: 
          fetch-depth: 0

      - name : Setup Bun
        uses : oven-sh/setup-bun@v2

      - name : Install dependencies
        run : bun install
        working-directory: ./backend


      - name : Run tests
        run : bun test
        working-directory: ./backend


  build-and-push-backend :
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      image_tag: ${{ steps.release.outputs.version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract release version
        id: release
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/release/* ]]; then
            VERSION=${GITHUB_REF#refs/heads/release/}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Extract backend metadata
        id: backend_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/backend
          tags : |
            type=raw,value=${{ steps.release.outputs.version }}
            type=sha,format=short

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.backend_meta.outputs.tags }}
  
  build-and-push-frontend :
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.ref == 'refs/heads/main')
    runs-on: ubuntu-latest
    timeout-minutes: 20
    outputs:
      image_tag: ${{ steps.release.outputs.version }}

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Extract release version
        id: release
        run: |
          if [[ "${GITHUB_REF}" == refs/heads/release/* ]]; then
            VERSION=${GITHUB_REF#refs/heads/release/}
            echo "version=$VERSION" >> $GITHUB_OUTPUT
          else
            echo "version=latest" >> $GITHUB_OUTPUT
          fi

      - name: Extract frontend metadata
        id: frontend_meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend
          tags : |
            type=raw,value=${{ steps.release.outputs.version }}
            type=sha,format=short

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
        
      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ${{ steps.frontend_meta.outputs.tags }}

  snyk-security:
    needs: linting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      - name: Install Snyk CLI
        run: npm install -g snyk

      # --- SCAN FRONTEND ---
      - name: Install Frontend Dependencies
        working-directory: ./frontend
        run: bun install

      - name: Scan Frontend
        working-directory: ./frontend
        # On utilise --auth pour être sûr que le token passe bien
        run: snyk test --auth=${{ secrets.SNYK_TOKEN }}

      # --- SCAN BACKEND ---
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: bun install

      - name: Scan Backend
        working-directory: ./backend
        run: snyk test --auth=${{ secrets.SNYK_TOKEN }}
  
  deploy-application:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: [build-and-push-backend, build-and-push-frontend]
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: copy docker-compose.yml and nginx.conf to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker-compose-server.yml,nginx.conf"
          target: ~/

      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            IMAGE_TAG="${{ needs.build-and-push-backend.outputs.image_tag }}"
            if [ -z "$IMAGE_TAG" ]; then
              echo "Error: IMAGE_TAG is not set. Exiting."
              exit 1
            fi
            cd ~
            docker compose -f docker-compose-server.yml down || true
            docker image prune -f || true
            docker pull ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/backend:${IMAGE_TAG}
            docker pull ${{ env.REGISTRY }}/${{ env.REPOSITORY }}/frontend:${IMAGE_TAG}
            IMAGE_TAG=${IMAGE_TAG} docker compose -f docker-compose-server.yml up -d